// Generated by gencpp from file moveto/Grab.msg
// DO NOT EDIT!


#ifndef MOVETO_MESSAGE_GRAB_H
#define MOVETO_MESSAGE_GRAB_H

#include <ros/service_traits.h>


#include <moveto/GrabRequest.h>
#include <moveto/GrabResponse.h>


namespace moveto
{

struct Grab
{

typedef GrabRequest Request;
typedef GrabResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Grab
} // namespace moveto


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::moveto::Grab > {
  static const char* value()
  {
    return "7ef6f7fbf0f84bb5331bcdbdad3a6022";
  }

  static const char* value(const ::moveto::Grab&) { return value(); }
};

template<>
struct DataType< ::moveto::Grab > {
  static const char* value()
  {
    return "moveto/Grab";
  }

  static const char* value(const ::moveto::Grab&) { return value(); }
};


// service_traits::MD5Sum< ::moveto::GrabRequest> should match 
// service_traits::MD5Sum< ::moveto::Grab > 
template<>
struct MD5Sum< ::moveto::GrabRequest>
{
  static const char* value()
  {
    return MD5Sum< ::moveto::Grab >::value();
  }
  static const char* value(const ::moveto::GrabRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::moveto::GrabRequest> should match 
// service_traits::DataType< ::moveto::Grab > 
template<>
struct DataType< ::moveto::GrabRequest>
{
  static const char* value()
  {
    return DataType< ::moveto::Grab >::value();
  }
  static const char* value(const ::moveto::GrabRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::moveto::GrabResponse> should match 
// service_traits::MD5Sum< ::moveto::Grab > 
template<>
struct MD5Sum< ::moveto::GrabResponse>
{
  static const char* value()
  {
    return MD5Sum< ::moveto::Grab >::value();
  }
  static const char* value(const ::moveto::GrabResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::moveto::GrabResponse> should match 
// service_traits::DataType< ::moveto::Grab > 
template<>
struct DataType< ::moveto::GrabResponse>
{
  static const char* value()
  {
    return DataType< ::moveto::Grab >::value();
  }
  static const char* value(const ::moveto::GrabResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVETO_MESSAGE_GRAB_H
