// Generated by gencpp from file moveto/IKinResponse.msg
// DO NOT EDIT!


#ifndef MOVETO_MESSAGE_IKINRESPONSE_H
#define MOVETO_MESSAGE_IKINRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <moveto/Joints.h>

namespace moveto
{
template <class ContainerAllocator>
struct IKinResponse_
{
  typedef IKinResponse_<ContainerAllocator> Type;

  IKinResponse_()
    : singular(false)
    , joints()  {
    }
  IKinResponse_(const ContainerAllocator& _alloc)
    : singular(false)
    , joints(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _singular_type;
  _singular_type singular;

   typedef  ::moveto::Joints_<ContainerAllocator>  _joints_type;
  _joints_type joints;





  typedef boost::shared_ptr< ::moveto::IKinResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::moveto::IKinResponse_<ContainerAllocator> const> ConstPtr;

}; // struct IKinResponse_

typedef ::moveto::IKinResponse_<std::allocator<void> > IKinResponse;

typedef boost::shared_ptr< ::moveto::IKinResponse > IKinResponsePtr;
typedef boost::shared_ptr< ::moveto::IKinResponse const> IKinResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::moveto::IKinResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::moveto::IKinResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace moveto

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'moveto': ['/home/adam/ros_ws/src/moveto/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::moveto::IKinResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::moveto::IKinResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::moveto::IKinResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::moveto::IKinResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::moveto::IKinResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::moveto::IKinResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::moveto::IKinResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4b88afb7b371e9f0c4b005efd5498579";
  }

  static const char* value(const ::moveto::IKinResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4b88afb7b371e9f0ULL;
  static const uint64_t static_value2 = 0xc4b005efd5498579ULL;
};

template<class ContainerAllocator>
struct DataType< ::moveto::IKinResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "moveto/IKinResponse";
  }

  static const char* value(const ::moveto::IKinResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::moveto::IKinResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
\n\
\n\
bool    singular\n\
Joints  joints\n\
\n\
\n\
================================================================================\n\
MSG: moveto/Joints\n\
# Message of joint values\n\
float64[5] joint\n\
";
  }

  static const char* value(const ::moveto::IKinResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::moveto::IKinResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.singular);
      stream.next(m.joints);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct IKinResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::moveto::IKinResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::moveto::IKinResponse_<ContainerAllocator>& v)
  {
    s << indent << "singular: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.singular);
    s << indent << "joints: ";
    s << std::endl;
    Printer< ::moveto::Joints_<ContainerAllocator> >::stream(s, indent + "  ", v.joints);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVETO_MESSAGE_IKINRESPONSE_H
