// Generated by gencpp from file moveto/Joints.msg
// DO NOT EDIT!


#ifndef MOVETO_MESSAGE_JOINTS_H
#define MOVETO_MESSAGE_JOINTS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace moveto
{
template <class ContainerAllocator>
struct Joints_
{
  typedef Joints_<ContainerAllocator> Type;

  Joints_()
    : joint()  {
      joint.assign(0.0);
  }
  Joints_(const ContainerAllocator& _alloc)
    : joint()  {
  (void)_alloc;
      joint.assign(0.0);
  }



   typedef boost::array<double, 5>  _joint_type;
  _joint_type joint;





  typedef boost::shared_ptr< ::moveto::Joints_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::moveto::Joints_<ContainerAllocator> const> ConstPtr;

}; // struct Joints_

typedef ::moveto::Joints_<std::allocator<void> > Joints;

typedef boost::shared_ptr< ::moveto::Joints > JointsPtr;
typedef boost::shared_ptr< ::moveto::Joints const> JointsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::moveto::Joints_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::moveto::Joints_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace moveto

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'moveto': ['/home/robot/ros_ws/src/moveto/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::moveto::Joints_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::moveto::Joints_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::moveto::Joints_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::moveto::Joints_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::moveto::Joints_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::moveto::Joints_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::moveto::Joints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a9cf03bac18e6f9d1321d10ce4de88b6";
  }

  static const char* value(const ::moveto::Joints_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa9cf03bac18e6f9dULL;
  static const uint64_t static_value2 = 0x1321d10ce4de88b6ULL;
};

template<class ContainerAllocator>
struct DataType< ::moveto::Joints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "moveto/Joints";
  }

  static const char* value(const ::moveto::Joints_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::moveto::Joints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Message of joint values\n\
float64[5] joint\n\
";
  }

  static const char* value(const ::moveto::Joints_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::moveto::Joints_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joint);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Joints_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::moveto::Joints_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::moveto::Joints_<ContainerAllocator>& v)
  {
    s << indent << "joint[]" << std::endl;
    for (size_t i = 0; i < v.joint.size(); ++i)
    {
      s << indent << "  joint[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.joint[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVETO_MESSAGE_JOINTS_H
