// Generated by gencpp from file moveto/MoveJoints.msg
// DO NOT EDIT!


#ifndef MOVETO_MESSAGE_MOVEJOINTS_H
#define MOVETO_MESSAGE_MOVEJOINTS_H

#include <ros/service_traits.h>


#include <moveto/MoveJointsRequest.h>
#include <moveto/MoveJointsResponse.h>


namespace moveto
{

struct MoveJoints
{

typedef MoveJointsRequest Request;
typedef MoveJointsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoveJoints
} // namespace moveto


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::moveto::MoveJoints > {
  static const char* value()
  {
    return "3df56d60d4f290ecf5ea26686d6c3967";
  }

  static const char* value(const ::moveto::MoveJoints&) { return value(); }
};

template<>
struct DataType< ::moveto::MoveJoints > {
  static const char* value()
  {
    return "moveto/MoveJoints";
  }

  static const char* value(const ::moveto::MoveJoints&) { return value(); }
};


// service_traits::MD5Sum< ::moveto::MoveJointsRequest> should match 
// service_traits::MD5Sum< ::moveto::MoveJoints > 
template<>
struct MD5Sum< ::moveto::MoveJointsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::moveto::MoveJoints >::value();
  }
  static const char* value(const ::moveto::MoveJointsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::moveto::MoveJointsRequest> should match 
// service_traits::DataType< ::moveto::MoveJoints > 
template<>
struct DataType< ::moveto::MoveJointsRequest>
{
  static const char* value()
  {
    return DataType< ::moveto::MoveJoints >::value();
  }
  static const char* value(const ::moveto::MoveJointsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::moveto::MoveJointsResponse> should match 
// service_traits::MD5Sum< ::moveto::MoveJoints > 
template<>
struct MD5Sum< ::moveto::MoveJointsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::moveto::MoveJoints >::value();
  }
  static const char* value(const ::moveto::MoveJointsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::moveto::MoveJointsResponse> should match 
// service_traits::DataType< ::moveto::MoveJoints > 
template<>
struct DataType< ::moveto::MoveJointsResponse>
{
  static const char* value()
  {
    return DataType< ::moveto::MoveJoints >::value();
  }
  static const char* value(const ::moveto::MoveJointsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVETO_MESSAGE_MOVEJOINTS_H
