// Generated by gencpp from file moveto/MoveTipRequest.msg
// DO NOT EDIT!


#ifndef MOVETO_MESSAGE_MOVETIPREQUEST_H
#define MOVETO_MESSAGE_MOVETIPREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <moveto/Tip.h>

namespace moveto
{
template <class ContainerAllocator>
struct MoveTipRequest_
{
  typedef MoveTipRequest_<ContainerAllocator> Type;

  MoveTipRequest_()
    : tip()  {
    }
  MoveTipRequest_(const ContainerAllocator& _alloc)
    : tip(_alloc)  {
  (void)_alloc;
    }



   typedef  ::moveto::Tip_<ContainerAllocator>  _tip_type;
  _tip_type tip;





  typedef boost::shared_ptr< ::moveto::MoveTipRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::moveto::MoveTipRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MoveTipRequest_

typedef ::moveto::MoveTipRequest_<std::allocator<void> > MoveTipRequest;

typedef boost::shared_ptr< ::moveto::MoveTipRequest > MoveTipRequestPtr;
typedef boost::shared_ptr< ::moveto::MoveTipRequest const> MoveTipRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::moveto::MoveTipRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::moveto::MoveTipRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace moveto

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'moveto': ['/home/robot/ros_ws/src/moveto/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::moveto::MoveTipRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::moveto::MoveTipRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::moveto::MoveTipRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::moveto::MoveTipRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::moveto::MoveTipRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::moveto::MoveTipRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::moveto::MoveTipRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8cbaf4d4c4662d317de5c178f210e33f";
  }

  static const char* value(const ::moveto::MoveTipRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8cbaf4d4c4662d31ULL;
  static const uint64_t static_value2 = 0x7de5c178f210e33fULL;
};

template<class ContainerAllocator>
struct DataType< ::moveto::MoveTipRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "moveto/MoveTipRequest";
  }

  static const char* value(const ::moveto::MoveTipRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::moveto::MoveTipRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
\n\
\n\
Tip     tip\n\
\n\
================================================================================\n\
MSG: moveto/Tip\n\
# Message of tip values\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 pitch\n\
float64 roll\n\
";
  }

  static const char* value(const ::moveto::MoveTipRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::moveto::MoveTipRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.tip);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveTipRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::moveto::MoveTipRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::moveto::MoveTipRequest_<ContainerAllocator>& v)
  {
    s << indent << "tip: ";
    s << std::endl;
    Printer< ::moveto::Tip_<ContainerAllocator> >::stream(s, indent + "  ", v.tip);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVETO_MESSAGE_MOVETIPREQUEST_H
