// Generated by gencpp from file moveto/ThrowTo.msg
// DO NOT EDIT!


#ifndef MOVETO_MESSAGE_THROWTO_H
#define MOVETO_MESSAGE_THROWTO_H

#include <ros/service_traits.h>


#include <moveto/ThrowToRequest.h>
#include <moveto/ThrowToResponse.h>


namespace moveto
{

struct ThrowTo
{

typedef ThrowToRequest Request;
typedef ThrowToResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ThrowTo
} // namespace moveto


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::moveto::ThrowTo > {
  static const char* value()
  {
    return "f5d911aee700e2e2bb9670f06078b78f";
  }

  static const char* value(const ::moveto::ThrowTo&) { return value(); }
};

template<>
struct DataType< ::moveto::ThrowTo > {
  static const char* value()
  {
    return "moveto/ThrowTo";
  }

  static const char* value(const ::moveto::ThrowTo&) { return value(); }
};


// service_traits::MD5Sum< ::moveto::ThrowToRequest> should match 
// service_traits::MD5Sum< ::moveto::ThrowTo > 
template<>
struct MD5Sum< ::moveto::ThrowToRequest>
{
  static const char* value()
  {
    return MD5Sum< ::moveto::ThrowTo >::value();
  }
  static const char* value(const ::moveto::ThrowToRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::moveto::ThrowToRequest> should match 
// service_traits::DataType< ::moveto::ThrowTo > 
template<>
struct DataType< ::moveto::ThrowToRequest>
{
  static const char* value()
  {
    return DataType< ::moveto::ThrowTo >::value();
  }
  static const char* value(const ::moveto::ThrowToRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::moveto::ThrowToResponse> should match 
// service_traits::MD5Sum< ::moveto::ThrowTo > 
template<>
struct MD5Sum< ::moveto::ThrowToResponse>
{
  static const char* value()
  {
    return MD5Sum< ::moveto::ThrowTo >::value();
  }
  static const char* value(const ::moveto::ThrowToResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::moveto::ThrowToResponse> should match 
// service_traits::DataType< ::moveto::ThrowTo > 
template<>
struct DataType< ::moveto::ThrowToResponse>
{
  static const char* value()
  {
    return DataType< ::moveto::ThrowTo >::value();
  }
  static const char* value(const ::moveto::ThrowToResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVETO_MESSAGE_THROWTO_H
