(cl:in-package hebiros-msg)
(cl:export '(NAME-VAL
          NAME
          KP-VAL
          KP
          KI-VAL
          KI
          KD-VAL
          KD
          FEED_FORWARD-VAL
          FEED_FORWARD
          DEAD_ZONE-VAL
          DEAD_ZONE
          I_CLAMP-VAL
          I_CLAMP
          PUNCH-VAL
          PUNCH
          MIN_TARGET-VAL
          MIN_TARGET
          MAX_TARGET-VAL
          MAX_TARGET
          TARGET_LOWPASS-VAL
          TARGET_LOWPASS
          MIN_OUTPUT-VAL
          MIN_OUTPUT
          MAX_OUTPUT-VAL
          MAX_OUTPUT
          OUTPUT_LOWPASS-VAL
          OUTPUT_LOWPASS
          D_ON_ERROR-VAL
          D_ON_ERROR
))