// Generated by gencpp from file hebiros/AddGroupFromNamesSrv.msg
// DO NOT EDIT!


#ifndef HEBIROS_MESSAGE_ADDGROUPFROMNAMESSRV_H
#define HEBIROS_MESSAGE_ADDGROUPFROMNAMESSRV_H

#include <ros/service_traits.h>


#include <hebiros/AddGroupFromNamesSrvRequest.h>
#include <hebiros/AddGroupFromNamesSrvResponse.h>


namespace hebiros
{

struct AddGroupFromNamesSrv
{

typedef AddGroupFromNamesSrvRequest Request;
typedef AddGroupFromNamesSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddGroupFromNamesSrv
} // namespace hebiros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hebiros::AddGroupFromNamesSrv > {
  static const char* value()
  {
    return "a31d701a4ec2a831130fc40890ab943d";
  }

  static const char* value(const ::hebiros::AddGroupFromNamesSrv&) { return value(); }
};

template<>
struct DataType< ::hebiros::AddGroupFromNamesSrv > {
  static const char* value()
  {
    return "hebiros/AddGroupFromNamesSrv";
  }

  static const char* value(const ::hebiros::AddGroupFromNamesSrv&) { return value(); }
};


// service_traits::MD5Sum< ::hebiros::AddGroupFromNamesSrvRequest> should match 
// service_traits::MD5Sum< ::hebiros::AddGroupFromNamesSrv > 
template<>
struct MD5Sum< ::hebiros::AddGroupFromNamesSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hebiros::AddGroupFromNamesSrv >::value();
  }
  static const char* value(const ::hebiros::AddGroupFromNamesSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hebiros::AddGroupFromNamesSrvRequest> should match 
// service_traits::DataType< ::hebiros::AddGroupFromNamesSrv > 
template<>
struct DataType< ::hebiros::AddGroupFromNamesSrvRequest>
{
  static const char* value()
  {
    return DataType< ::hebiros::AddGroupFromNamesSrv >::value();
  }
  static const char* value(const ::hebiros::AddGroupFromNamesSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hebiros::AddGroupFromNamesSrvResponse> should match 
// service_traits::MD5Sum< ::hebiros::AddGroupFromNamesSrv > 
template<>
struct MD5Sum< ::hebiros::AddGroupFromNamesSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hebiros::AddGroupFromNamesSrv >::value();
  }
  static const char* value(const ::hebiros::AddGroupFromNamesSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hebiros::AddGroupFromNamesSrvResponse> should match 
// service_traits::DataType< ::hebiros::AddGroupFromNamesSrv > 
template<>
struct DataType< ::hebiros::AddGroupFromNamesSrvResponse>
{
  static const char* value()
  {
    return DataType< ::hebiros::AddGroupFromNamesSrv >::value();
  }
  static const char* value(const ::hebiros::AddGroupFromNamesSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HEBIROS_MESSAGE_ADDGROUPFROMNAMESSRV_H
