// Generated by gencpp from file hebiros/AddGroupFromUrdfSrvRequest.msg
// DO NOT EDIT!


#ifndef HEBIROS_MESSAGE_ADDGROUPFROMURDFSRVREQUEST_H
#define HEBIROS_MESSAGE_ADDGROUPFROMURDFSRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hebiros
{
template <class ContainerAllocator>
struct AddGroupFromUrdfSrvRequest_
{
  typedef AddGroupFromUrdfSrvRequest_<ContainerAllocator> Type;

  AddGroupFromUrdfSrvRequest_()
    : group_name()  {
    }
  AddGroupFromUrdfSrvRequest_(const ContainerAllocator& _alloc)
    : group_name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _group_name_type;
  _group_name_type group_name;





  typedef boost::shared_ptr< ::hebiros::AddGroupFromUrdfSrvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hebiros::AddGroupFromUrdfSrvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct AddGroupFromUrdfSrvRequest_

typedef ::hebiros::AddGroupFromUrdfSrvRequest_<std::allocator<void> > AddGroupFromUrdfSrvRequest;

typedef boost::shared_ptr< ::hebiros::AddGroupFromUrdfSrvRequest > AddGroupFromUrdfSrvRequestPtr;
typedef boost::shared_ptr< ::hebiros::AddGroupFromUrdfSrvRequest const> AddGroupFromUrdfSrvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hebiros::AddGroupFromUrdfSrvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hebiros::AddGroupFromUrdfSrvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hebiros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/melodic/share/sensor_msgs/cmake/../msg'], 'hebiros': ['/home/robot/hebi_ros_ws/src/hebiros/hebiros/msg', '/home/robot/hebi_ros_ws/devel/share/hebiros/msg'], 'actionlib_msgs': ['/opt/ros/melodic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hebiros::AddGroupFromUrdfSrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hebiros::AddGroupFromUrdfSrvRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hebiros::AddGroupFromUrdfSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hebiros::AddGroupFromUrdfSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hebiros::AddGroupFromUrdfSrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hebiros::AddGroupFromUrdfSrvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hebiros::AddGroupFromUrdfSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "967d0b0c0d858ded8a6a69abbce0c981";
  }

  static const char* value(const ::hebiros::AddGroupFromUrdfSrvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x967d0b0c0d858dedULL;
  static const uint64_t static_value2 = 0x8a6a69abbce0c981ULL;
};

template<class ContainerAllocator>
struct DataType< ::hebiros::AddGroupFromUrdfSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hebiros/AddGroupFromUrdfSrvRequest";
  }

  static const char* value(const ::hebiros::AddGroupFromUrdfSrvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hebiros::AddGroupFromUrdfSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string group_name\n\
";
  }

  static const char* value(const ::hebiros::AddGroupFromUrdfSrvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hebiros::AddGroupFromUrdfSrvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.group_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AddGroupFromUrdfSrvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hebiros::AddGroupFromUrdfSrvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hebiros::AddGroupFromUrdfSrvRequest_<ContainerAllocator>& v)
  {
    s << indent << "group_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.group_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HEBIROS_MESSAGE_ADDGROUPFROMURDFSRVREQUEST_H
