// Generated by gencpp from file hebiros/AddGroupFromNamesSrvRequest.msg
// DO NOT EDIT!


#ifndef HEBIROS_MESSAGE_ADDGROUPFROMNAMESSRVREQUEST_H
#define HEBIROS_MESSAGE_ADDGROUPFROMNAMESSRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hebiros
{
template <class ContainerAllocator>
struct AddGroupFromNamesSrvRequest_
{
  typedef AddGroupFromNamesSrvRequest_<ContainerAllocator> Type;

  AddGroupFromNamesSrvRequest_()
    : group_name()
    , names()
    , families()  {
    }
  AddGroupFromNamesSrvRequest_(const ContainerAllocator& _alloc)
    : group_name(_alloc)
    , names(_alloc)
    , families(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _group_name_type;
  _group_name_type group_name;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _names_type;
  _names_type names;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _families_type;
  _families_type families;





  typedef boost::shared_ptr< ::hebiros::AddGroupFromNamesSrvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hebiros::AddGroupFromNamesSrvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct AddGroupFromNamesSrvRequest_

typedef ::hebiros::AddGroupFromNamesSrvRequest_<std::allocator<void> > AddGroupFromNamesSrvRequest;

typedef boost::shared_ptr< ::hebiros::AddGroupFromNamesSrvRequest > AddGroupFromNamesSrvRequestPtr;
typedef boost::shared_ptr< ::hebiros::AddGroupFromNamesSrvRequest const> AddGroupFromNamesSrvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hebiros::AddGroupFromNamesSrvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hebiros::AddGroupFromNamesSrvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hebiros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/melodic/share/sensor_msgs/cmake/../msg'], 'hebiros': ['/home/robot/hebi_ros_ws/src/hebiros/hebiros/msg', '/home/robot/hebi_ros_ws/devel/share/hebiros/msg'], 'actionlib_msgs': ['/opt/ros/melodic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hebiros::AddGroupFromNamesSrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hebiros::AddGroupFromNamesSrvRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hebiros::AddGroupFromNamesSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hebiros::AddGroupFromNamesSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hebiros::AddGroupFromNamesSrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hebiros::AddGroupFromNamesSrvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hebiros::AddGroupFromNamesSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a31d701a4ec2a831130fc40890ab943d";
  }

  static const char* value(const ::hebiros::AddGroupFromNamesSrvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa31d701a4ec2a831ULL;
  static const uint64_t static_value2 = 0x130fc40890ab943dULL;
};

template<class ContainerAllocator>
struct DataType< ::hebiros::AddGroupFromNamesSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hebiros/AddGroupFromNamesSrvRequest";
  }

  static const char* value(const ::hebiros::AddGroupFromNamesSrvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hebiros::AddGroupFromNamesSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string group_name\n\
string[] names\n\
string[] families\n\
";
  }

  static const char* value(const ::hebiros::AddGroupFromNamesSrvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hebiros::AddGroupFromNamesSrvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.group_name);
      stream.next(m.names);
      stream.next(m.families);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AddGroupFromNamesSrvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hebiros::AddGroupFromNamesSrvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hebiros::AddGroupFromNamesSrvRequest_<ContainerAllocator>& v)
  {
    s << indent << "group_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.group_name);
    s << indent << "names[]" << std::endl;
    for (size_t i = 0; i < v.names.size(); ++i)
    {
      s << indent << "  names[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.names[i]);
    }
    s << indent << "families[]" << std::endl;
    for (size_t i = 0; i < v.families.size(); ++i)
    {
      s << indent << "  families[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.families[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // HEBIROS_MESSAGE_ADDGROUPFROMNAMESSRVREQUEST_H
