// Generated by gencpp from file hebiros/EntryListSrvResponse.msg
// DO NOT EDIT!


#ifndef HEBIROS_MESSAGE_ENTRYLISTSRVRESPONSE_H
#define HEBIROS_MESSAGE_ENTRYLISTSRVRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <hebiros/EntryListMsg.h>

namespace hebiros
{
template <class ContainerAllocator>
struct EntryListSrvResponse_
{
  typedef EntryListSrvResponse_<ContainerAllocator> Type;

  EntryListSrvResponse_()
    : entry_list()  {
    }
  EntryListSrvResponse_(const ContainerAllocator& _alloc)
    : entry_list(_alloc)  {
  (void)_alloc;
    }



   typedef  ::hebiros::EntryListMsg_<ContainerAllocator>  _entry_list_type;
  _entry_list_type entry_list;





  typedef boost::shared_ptr< ::hebiros::EntryListSrvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hebiros::EntryListSrvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct EntryListSrvResponse_

typedef ::hebiros::EntryListSrvResponse_<std::allocator<void> > EntryListSrvResponse;

typedef boost::shared_ptr< ::hebiros::EntryListSrvResponse > EntryListSrvResponsePtr;
typedef boost::shared_ptr< ::hebiros::EntryListSrvResponse const> EntryListSrvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hebiros::EntryListSrvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hebiros::EntryListSrvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hebiros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/melodic/share/sensor_msgs/cmake/../msg'], 'hebiros': ['/home/robot/hebi_ros_ws/src/hebiros/hebiros/msg', '/home/robot/hebi_ros_ws/devel/share/hebiros/msg'], 'actionlib_msgs': ['/opt/ros/melodic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hebiros::EntryListSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hebiros::EntryListSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hebiros::EntryListSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hebiros::EntryListSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hebiros::EntryListSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hebiros::EntryListSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hebiros::EntryListSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "019fcca877608da550bd2d6857203482";
  }

  static const char* value(const ::hebiros::EntryListSrvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x019fcca877608da5ULL;
  static const uint64_t static_value2 = 0x50bd2d6857203482ULL;
};

template<class ContainerAllocator>
struct DataType< ::hebiros::EntryListSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hebiros/EntryListSrvResponse";
  }

  static const char* value(const ::hebiros::EntryListSrvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hebiros::EntryListSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "EntryListMsg entry_list\n\
\n\
\n\
================================================================================\n\
MSG: hebiros/EntryListMsg\n\
int32 size\n\
hebiros/EntryMsg[] entries\n\
\n\
================================================================================\n\
MSG: hebiros/EntryMsg\n\
string name\n\
string family\n\
int64 mac_address\n\
";
  }

  static const char* value(const ::hebiros::EntryListSrvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hebiros::EntryListSrvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.entry_list);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EntryListSrvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hebiros::EntryListSrvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hebiros::EntryListSrvResponse_<ContainerAllocator>& v)
  {
    s << indent << "entry_list: ";
    s << std::endl;
    Printer< ::hebiros::EntryListMsg_<ContainerAllocator> >::stream(s, indent + "  ", v.entry_list);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HEBIROS_MESSAGE_ENTRYLISTSRVRESPONSE_H
