// Generated by gencpp from file hebiros/EntryListSrv.msg
// DO NOT EDIT!


#ifndef HEBIROS_MESSAGE_ENTRYLISTSRV_H
#define HEBIROS_MESSAGE_ENTRYLISTSRV_H

#include <ros/service_traits.h>


#include <hebiros/EntryListSrvRequest.h>
#include <hebiros/EntryListSrvResponse.h>


namespace hebiros
{

struct EntryListSrv
{

typedef EntryListSrvRequest Request;
typedef EntryListSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct EntryListSrv
} // namespace hebiros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hebiros::EntryListSrv > {
  static const char* value()
  {
    return "019fcca877608da550bd2d6857203482";
  }

  static const char* value(const ::hebiros::EntryListSrv&) { return value(); }
};

template<>
struct DataType< ::hebiros::EntryListSrv > {
  static const char* value()
  {
    return "hebiros/EntryListSrv";
  }

  static const char* value(const ::hebiros::EntryListSrv&) { return value(); }
};


// service_traits::MD5Sum< ::hebiros::EntryListSrvRequest> should match 
// service_traits::MD5Sum< ::hebiros::EntryListSrv > 
template<>
struct MD5Sum< ::hebiros::EntryListSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hebiros::EntryListSrv >::value();
  }
  static const char* value(const ::hebiros::EntryListSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hebiros::EntryListSrvRequest> should match 
// service_traits::DataType< ::hebiros::EntryListSrv > 
template<>
struct DataType< ::hebiros::EntryListSrvRequest>
{
  static const char* value()
  {
    return DataType< ::hebiros::EntryListSrv >::value();
  }
  static const char* value(const ::hebiros::EntryListSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hebiros::EntryListSrvResponse> should match 
// service_traits::MD5Sum< ::hebiros::EntryListSrv > 
template<>
struct MD5Sum< ::hebiros::EntryListSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hebiros::EntryListSrv >::value();
  }
  static const char* value(const ::hebiros::EntryListSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hebiros::EntryListSrvResponse> should match 
// service_traits::DataType< ::hebiros::EntryListSrv > 
template<>
struct DataType< ::hebiros::EntryListSrvResponse>
{
  static const char* value()
  {
    return DataType< ::hebiros::EntryListSrv >::value();
  }
  static const char* value(const ::hebiros::EntryListSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HEBIROS_MESSAGE_ENTRYLISTSRV_H
