// Generated by gencpp from file hebiros/SendCommandWithAcknowledgementSrv.msg
// DO NOT EDIT!


#ifndef HEBIROS_MESSAGE_SENDCOMMANDWITHACKNOWLEDGEMENTSRV_H
#define HEBIROS_MESSAGE_SENDCOMMANDWITHACKNOWLEDGEMENTSRV_H

#include <ros/service_traits.h>


#include <hebiros/SendCommandWithAcknowledgementSrvRequest.h>
#include <hebiros/SendCommandWithAcknowledgementSrvResponse.h>


namespace hebiros
{

struct SendCommandWithAcknowledgementSrv
{

typedef SendCommandWithAcknowledgementSrvRequest Request;
typedef SendCommandWithAcknowledgementSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SendCommandWithAcknowledgementSrv
} // namespace hebiros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hebiros::SendCommandWithAcknowledgementSrv > {
  static const char* value()
  {
    return "dc4cfbf8596ddaff00c6c17ca78326b7";
  }

  static const char* value(const ::hebiros::SendCommandWithAcknowledgementSrv&) { return value(); }
};

template<>
struct DataType< ::hebiros::SendCommandWithAcknowledgementSrv > {
  static const char* value()
  {
    return "hebiros/SendCommandWithAcknowledgementSrv";
  }

  static const char* value(const ::hebiros::SendCommandWithAcknowledgementSrv&) { return value(); }
};


// service_traits::MD5Sum< ::hebiros::SendCommandWithAcknowledgementSrvRequest> should match 
// service_traits::MD5Sum< ::hebiros::SendCommandWithAcknowledgementSrv > 
template<>
struct MD5Sum< ::hebiros::SendCommandWithAcknowledgementSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hebiros::SendCommandWithAcknowledgementSrv >::value();
  }
  static const char* value(const ::hebiros::SendCommandWithAcknowledgementSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hebiros::SendCommandWithAcknowledgementSrvRequest> should match 
// service_traits::DataType< ::hebiros::SendCommandWithAcknowledgementSrv > 
template<>
struct DataType< ::hebiros::SendCommandWithAcknowledgementSrvRequest>
{
  static const char* value()
  {
    return DataType< ::hebiros::SendCommandWithAcknowledgementSrv >::value();
  }
  static const char* value(const ::hebiros::SendCommandWithAcknowledgementSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hebiros::SendCommandWithAcknowledgementSrvResponse> should match 
// service_traits::MD5Sum< ::hebiros::SendCommandWithAcknowledgementSrv > 
template<>
struct MD5Sum< ::hebiros::SendCommandWithAcknowledgementSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hebiros::SendCommandWithAcknowledgementSrv >::value();
  }
  static const char* value(const ::hebiros::SendCommandWithAcknowledgementSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hebiros::SendCommandWithAcknowledgementSrvResponse> should match 
// service_traits::DataType< ::hebiros::SendCommandWithAcknowledgementSrv > 
template<>
struct DataType< ::hebiros::SendCommandWithAcknowledgementSrvResponse>
{
  static const char* value()
  {
    return DataType< ::hebiros::SendCommandWithAcknowledgementSrv >::value();
  }
  static const char* value(const ::hebiros::SendCommandWithAcknowledgementSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HEBIROS_MESSAGE_SENDCOMMANDWITHACKNOWLEDGEMENTSRV_H
