// Generated by gencpp from file hebiros/SetCommandLifetimeSrv.msg
// DO NOT EDIT!


#ifndef HEBIROS_MESSAGE_SETCOMMANDLIFETIMESRV_H
#define HEBIROS_MESSAGE_SETCOMMANDLIFETIMESRV_H

#include <ros/service_traits.h>


#include <hebiros/SetCommandLifetimeSrvRequest.h>
#include <hebiros/SetCommandLifetimeSrvResponse.h>


namespace hebiros
{

struct SetCommandLifetimeSrv
{

typedef SetCommandLifetimeSrvRequest Request;
typedef SetCommandLifetimeSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetCommandLifetimeSrv
} // namespace hebiros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hebiros::SetCommandLifetimeSrv > {
  static const char* value()
  {
    return "9e6d0becb75f24a1f3c269f4469e5d38";
  }

  static const char* value(const ::hebiros::SetCommandLifetimeSrv&) { return value(); }
};

template<>
struct DataType< ::hebiros::SetCommandLifetimeSrv > {
  static const char* value()
  {
    return "hebiros/SetCommandLifetimeSrv";
  }

  static const char* value(const ::hebiros::SetCommandLifetimeSrv&) { return value(); }
};


// service_traits::MD5Sum< ::hebiros::SetCommandLifetimeSrvRequest> should match 
// service_traits::MD5Sum< ::hebiros::SetCommandLifetimeSrv > 
template<>
struct MD5Sum< ::hebiros::SetCommandLifetimeSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hebiros::SetCommandLifetimeSrv >::value();
  }
  static const char* value(const ::hebiros::SetCommandLifetimeSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hebiros::SetCommandLifetimeSrvRequest> should match 
// service_traits::DataType< ::hebiros::SetCommandLifetimeSrv > 
template<>
struct DataType< ::hebiros::SetCommandLifetimeSrvRequest>
{
  static const char* value()
  {
    return DataType< ::hebiros::SetCommandLifetimeSrv >::value();
  }
  static const char* value(const ::hebiros::SetCommandLifetimeSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hebiros::SetCommandLifetimeSrvResponse> should match 
// service_traits::MD5Sum< ::hebiros::SetCommandLifetimeSrv > 
template<>
struct MD5Sum< ::hebiros::SetCommandLifetimeSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hebiros::SetCommandLifetimeSrv >::value();
  }
  static const char* value(const ::hebiros::SetCommandLifetimeSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hebiros::SetCommandLifetimeSrvResponse> should match 
// service_traits::DataType< ::hebiros::SetCommandLifetimeSrv > 
template<>
struct DataType< ::hebiros::SetCommandLifetimeSrvResponse>
{
  static const char* value()
  {
    return DataType< ::hebiros::SetCommandLifetimeSrv >::value();
  }
  static const char* value(const ::hebiros::SetCommandLifetimeSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HEBIROS_MESSAGE_SETCOMMANDLIFETIMESRV_H
