// Generated by gencpp from file hebiros/SetFeedbackFrequencySrv.msg
// DO NOT EDIT!


#ifndef HEBIROS_MESSAGE_SETFEEDBACKFREQUENCYSRV_H
#define HEBIROS_MESSAGE_SETFEEDBACKFREQUENCYSRV_H

#include <ros/service_traits.h>


#include <hebiros/SetFeedbackFrequencySrvRequest.h>
#include <hebiros/SetFeedbackFrequencySrvResponse.h>


namespace hebiros
{

struct SetFeedbackFrequencySrv
{

typedef SetFeedbackFrequencySrvRequest Request;
typedef SetFeedbackFrequencySrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetFeedbackFrequencySrv
} // namespace hebiros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hebiros::SetFeedbackFrequencySrv > {
  static const char* value()
  {
    return "89e470a7bc482c7199fa75ef40009369";
  }

  static const char* value(const ::hebiros::SetFeedbackFrequencySrv&) { return value(); }
};

template<>
struct DataType< ::hebiros::SetFeedbackFrequencySrv > {
  static const char* value()
  {
    return "hebiros/SetFeedbackFrequencySrv";
  }

  static const char* value(const ::hebiros::SetFeedbackFrequencySrv&) { return value(); }
};


// service_traits::MD5Sum< ::hebiros::SetFeedbackFrequencySrvRequest> should match 
// service_traits::MD5Sum< ::hebiros::SetFeedbackFrequencySrv > 
template<>
struct MD5Sum< ::hebiros::SetFeedbackFrequencySrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hebiros::SetFeedbackFrequencySrv >::value();
  }
  static const char* value(const ::hebiros::SetFeedbackFrequencySrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hebiros::SetFeedbackFrequencySrvRequest> should match 
// service_traits::DataType< ::hebiros::SetFeedbackFrequencySrv > 
template<>
struct DataType< ::hebiros::SetFeedbackFrequencySrvRequest>
{
  static const char* value()
  {
    return DataType< ::hebiros::SetFeedbackFrequencySrv >::value();
  }
  static const char* value(const ::hebiros::SetFeedbackFrequencySrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hebiros::SetFeedbackFrequencySrvResponse> should match 
// service_traits::MD5Sum< ::hebiros::SetFeedbackFrequencySrv > 
template<>
struct MD5Sum< ::hebiros::SetFeedbackFrequencySrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hebiros::SetFeedbackFrequencySrv >::value();
  }
  static const char* value(const ::hebiros::SetFeedbackFrequencySrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hebiros::SetFeedbackFrequencySrvResponse> should match 
// service_traits::DataType< ::hebiros::SetFeedbackFrequencySrv > 
template<>
struct DataType< ::hebiros::SetFeedbackFrequencySrvResponse>
{
  static const char* value()
  {
    return DataType< ::hebiros::SetFeedbackFrequencySrv >::value();
  }
  static const char* value(const ::hebiros::SetFeedbackFrequencySrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HEBIROS_MESSAGE_SETFEEDBACKFREQUENCYSRV_H
