// Generated by gencpp from file hebiros/SizeSrv.msg
// DO NOT EDIT!


#ifndef HEBIROS_MESSAGE_SIZESRV_H
#define HEBIROS_MESSAGE_SIZESRV_H

#include <ros/service_traits.h>


#include <hebiros/SizeSrvRequest.h>
#include <hebiros/SizeSrvResponse.h>


namespace hebiros
{

struct SizeSrv
{

typedef SizeSrvRequest Request;
typedef SizeSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SizeSrv
} // namespace hebiros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hebiros::SizeSrv > {
  static const char* value()
  {
    return "97da5de9999c5ce84f539773c8d0b2a3";
  }

  static const char* value(const ::hebiros::SizeSrv&) { return value(); }
};

template<>
struct DataType< ::hebiros::SizeSrv > {
  static const char* value()
  {
    return "hebiros/SizeSrv";
  }

  static const char* value(const ::hebiros::SizeSrv&) { return value(); }
};


// service_traits::MD5Sum< ::hebiros::SizeSrvRequest> should match 
// service_traits::MD5Sum< ::hebiros::SizeSrv > 
template<>
struct MD5Sum< ::hebiros::SizeSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hebiros::SizeSrv >::value();
  }
  static const char* value(const ::hebiros::SizeSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hebiros::SizeSrvRequest> should match 
// service_traits::DataType< ::hebiros::SizeSrv > 
template<>
struct DataType< ::hebiros::SizeSrvRequest>
{
  static const char* value()
  {
    return DataType< ::hebiros::SizeSrv >::value();
  }
  static const char* value(const ::hebiros::SizeSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hebiros::SizeSrvResponse> should match 
// service_traits::MD5Sum< ::hebiros::SizeSrv > 
template<>
struct MD5Sum< ::hebiros::SizeSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hebiros::SizeSrv >::value();
  }
  static const char* value(const ::hebiros::SizeSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hebiros::SizeSrvResponse> should match 
// service_traits::DataType< ::hebiros::SizeSrv > 
template<>
struct DataType< ::hebiros::SizeSrvResponse>
{
  static const char* value()
  {
    return DataType< ::hebiros::SizeSrv >::value();
  }
  static const char* value(const ::hebiros::SizeSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HEBIROS_MESSAGE_SIZESRV_H
