(cl:defpackage moveto-srv
  (:use )
  (:export
   "IKIN"
   "<IKIN-REQUEST>"
   "IKIN-REQUEST"
   "<IKIN-RESPONSE>"
   "IKIN-RESPONSE"
   "ISMOVING"
   "<ISMOVING-REQUEST>"
   "ISMOVING-REQUEST"
   "<ISMOVING-RESPONSE>"
   "ISMOVING-RESPONSE"
   "MOVEJOINTS"
   "<MOVEJOINTS-REQUEST>"
   "MOVEJOINTS-REQUEST"
   "<MOVEJOINTS-RESPONSE>"
   "MOVEJOINTS-RESPONSE"
   "MOVETIP"
   "<MOVETIP-REQUEST>"
   "MOVETIP-REQUEST"
   "<MOVETIP-RESPONSE>"
   "MOVETIP-RESPONSE"
  ))

