# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from hebiros/CommandMsg.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import hebiros.msg

class CommandMsg(genpy.Message):
  _md5sum = "bfeea03edefa65b3e88462912543b8b6"
  _type = "hebiros/CommandMsg"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """string[] name
float64[] position
float64[] velocity
float64[] effort
hebiros/SettingsMsg settings


================================================================================
MSG: hebiros/SettingsMsg
string[] name
bool[] save_current_settings
int8[] control_strategy
hebiros/PidGainsMsg position_gains
hebiros/PidGainsMsg velocity_gains
hebiros/PidGainsMsg effort_gains


================================================================================
MSG: hebiros/PidGainsMsg
string[] name
float64[] kp
float64[] ki
float64[] kd
float64[] feed_forward
float64[] dead_zone
float64[] i_clamp
float64[] punch
float64[] min_target
float64[] max_target
float64[] target_lowpass
float64[] min_output
float64[] max_output
float64[] output_lowpass
bool[] d_on_error

"""
  __slots__ = ['name','position','velocity','effort','settings']
  _slot_types = ['string[]','float64[]','float64[]','float64[]','hebiros/SettingsMsg']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       name,position,velocity,effort,settings

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(CommandMsg, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.name is None:
        self.name = []
      if self.position is None:
        self.position = []
      if self.velocity is None:
        self.velocity = []
      if self.effort is None:
        self.effort = []
      if self.settings is None:
        self.settings = hebiros.msg.SettingsMsg()
    else:
      self.name = []
      self.position = []
      self.velocity = []
      self.effort = []
      self.settings = hebiros.msg.SettingsMsg()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.name)
      buff.write(_struct_I.pack(length))
      for val1 in self.name:
        length = len(val1)
        if python3 or type(val1) == unicode:
          val1 = val1.encode('utf-8')
          length = len(val1)
        buff.write(struct.pack('<I%ss'%length, length, val1))
      length = len(self.position)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.position))
      length = len(self.velocity)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.velocity))
      length = len(self.effort)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.effort))
      length = len(self.settings.name)
      buff.write(_struct_I.pack(length))
      for val1 in self.settings.name:
        length = len(val1)
        if python3 or type(val1) == unicode:
          val1 = val1.encode('utf-8')
          length = len(val1)
        buff.write(struct.pack('<I%ss'%length, length, val1))
      length = len(self.settings.save_current_settings)
      buff.write(_struct_I.pack(length))
      pattern = '<%sB'%length
      buff.write(struct.pack(pattern, *self.settings.save_current_settings))
      length = len(self.settings.control_strategy)
      buff.write(_struct_I.pack(length))
      pattern = '<%sb'%length
      buff.write(struct.pack(pattern, *self.settings.control_strategy))
      length = len(self.settings.position_gains.name)
      buff.write(_struct_I.pack(length))
      for val1 in self.settings.position_gains.name:
        length = len(val1)
        if python3 or type(val1) == unicode:
          val1 = val1.encode('utf-8')
          length = len(val1)
        buff.write(struct.pack('<I%ss'%length, length, val1))
      length = len(self.settings.position_gains.kp)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.settings.position_gains.kp))
      length = len(self.settings.position_gains.ki)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.settings.position_gains.ki))
      length = len(self.settings.position_gains.kd)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.settings.position_gains.kd))
      length = len(self.settings.position_gains.feed_forward)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.settings.position_gains.feed_forward))
      length = len(self.settings.position_gains.dead_zone)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.settings.position_gains.dead_zone))
      length = len(self.settings.position_gains.i_clamp)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.settings.position_gains.i_clamp))
      length = len(self.settings.position_gains.punch)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.settings.position_gains.punch))
      length = len(self.settings.position_gains.min_target)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.settings.position_gains.min_target))
      length = len(self.settings.position_gains.max_target)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.settings.position_gains.max_target))
      length = len(self.settings.position_gains.target_lowpass)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.settings.position_gains.target_lowpass))
      length = len(self.settings.position_gains.min_output)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.settings.position_gains.min_output))
      length = len(self.settings.position_gains.max_output)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.settings.position_gains.max_output))
      length = len(self.settings.position_gains.output_lowpass)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.settings.position_gains.output_lowpass))
      length = len(self.settings.position_gains.d_on_error)
      buff.write(_struct_I.pack(length))
      pattern = '<%sB'%length
      buff.write(struct.pack(pattern, *self.settings.position_gains.d_on_error))
      length = len(self.settings.velocity_gains.name)
      buff.write(_struct_I.pack(length))
      for val1 in self.settings.velocity_gains.name:
        length = len(val1)
        if python3 or type(val1) == unicode:
          val1 = val1.encode('utf-8')
          length = len(val1)
        buff.write(struct.pack('<I%ss'%length, length, val1))
      length = len(self.settings.velocity_gains.kp)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.settings.velocity_gains.kp))
      length = len(self.settings.velocity_gains.ki)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.settings.velocity_gains.ki))
      length = len(self.settings.velocity_gains.kd)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.settings.velocity_gains.kd))
      length = len(self.settings.velocity_gains.feed_forward)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.settings.velocity_gains.feed_forward))
      length = len(self.settings.velocity_gains.dead_zone)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.settings.velocity_gains.dead_zone))
      length = len(self.settings.velocity_gains.i_clamp)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.settings.velocity_gains.i_clamp))
      length = len(self.settings.velocity_gains.punch)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.settings.velocity_gains.punch))
      length = len(self.settings.velocity_gains.min_target)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.settings.velocity_gains.min_target))
      length = len(self.settings.velocity_gains.max_target)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.settings.velocity_gains.max_target))
      length = len(self.settings.velocity_gains.target_lowpass)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.settings.velocity_gains.target_lowpass))
      length = len(self.settings.velocity_gains.min_output)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.settings.velocity_gains.min_output))
      length = len(self.settings.velocity_gains.max_output)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.settings.velocity_gains.max_output))
      length = len(self.settings.velocity_gains.output_lowpass)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.settings.velocity_gains.output_lowpass))
      length = len(self.settings.velocity_gains.d_on_error)
      buff.write(_struct_I.pack(length))
      pattern = '<%sB'%length
      buff.write(struct.pack(pattern, *self.settings.velocity_gains.d_on_error))
      length = len(self.settings.effort_gains.name)
      buff.write(_struct_I.pack(length))
      for val1 in self.settings.effort_gains.name:
        length = len(val1)
        if python3 or type(val1) == unicode:
          val1 = val1.encode('utf-8')
          length = len(val1)
        buff.write(struct.pack('<I%ss'%length, length, val1))
      length = len(self.settings.effort_gains.kp)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.settings.effort_gains.kp))
      length = len(self.settings.effort_gains.ki)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.settings.effort_gains.ki))
      length = len(self.settings.effort_gains.kd)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.settings.effort_gains.kd))
      length = len(self.settings.effort_gains.feed_forward)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.settings.effort_gains.feed_forward))
      length = len(self.settings.effort_gains.dead_zone)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.settings.effort_gains.dead_zone))
      length = len(self.settings.effort_gains.i_clamp)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.settings.effort_gains.i_clamp))
      length = len(self.settings.effort_gains.punch)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.settings.effort_gains.punch))
      length = len(self.settings.effort_gains.min_target)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.settings.effort_gains.min_target))
      length = len(self.settings.effort_gains.max_target)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.settings.effort_gains.max_target))
      length = len(self.settings.effort_gains.target_lowpass)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.settings.effort_gains.target_lowpass))
      length = len(self.settings.effort_gains.min_output)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.settings.effort_gains.min_output))
      length = len(self.settings.effort_gains.max_output)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.settings.effort_gains.max_output))
      length = len(self.settings.effort_gains.output_lowpass)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.settings.effort_gains.output_lowpass))
      length = len(self.settings.effort_gains.d_on_error)
      buff.write(_struct_I.pack(length))
      pattern = '<%sB'%length
      buff.write(struct.pack(pattern, *self.settings.effort_gains.d_on_error))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.settings is None:
        self.settings = hebiros.msg.SettingsMsg()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.name = []
      for i in range(0, length):
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1 = str[start:end].decode('utf-8')
        else:
          val1 = str[start:end]
        self.name.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.position = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.velocity = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.effort = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.settings.name = []
      for i in range(0, length):
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1 = str[start:end].decode('utf-8')
        else:
          val1 = str[start:end]
        self.settings.name.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sB'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.save_current_settings = struct.unpack(pattern, str[start:end])
      self.settings.save_current_settings = map(bool, self.settings.save_current_settings)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sb'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.control_strategy = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.settings.position_gains.name = []
      for i in range(0, length):
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1 = str[start:end].decode('utf-8')
        else:
          val1 = str[start:end]
        self.settings.position_gains.name.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.position_gains.kp = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.position_gains.ki = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.position_gains.kd = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.position_gains.feed_forward = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.position_gains.dead_zone = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.position_gains.i_clamp = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.position_gains.punch = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.position_gains.min_target = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.position_gains.max_target = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.position_gains.target_lowpass = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.position_gains.min_output = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.position_gains.max_output = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.position_gains.output_lowpass = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sB'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.position_gains.d_on_error = struct.unpack(pattern, str[start:end])
      self.settings.position_gains.d_on_error = map(bool, self.settings.position_gains.d_on_error)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.settings.velocity_gains.name = []
      for i in range(0, length):
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1 = str[start:end].decode('utf-8')
        else:
          val1 = str[start:end]
        self.settings.velocity_gains.name.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.velocity_gains.kp = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.velocity_gains.ki = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.velocity_gains.kd = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.velocity_gains.feed_forward = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.velocity_gains.dead_zone = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.velocity_gains.i_clamp = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.velocity_gains.punch = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.velocity_gains.min_target = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.velocity_gains.max_target = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.velocity_gains.target_lowpass = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.velocity_gains.min_output = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.velocity_gains.max_output = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.velocity_gains.output_lowpass = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sB'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.velocity_gains.d_on_error = struct.unpack(pattern, str[start:end])
      self.settings.velocity_gains.d_on_error = map(bool, self.settings.velocity_gains.d_on_error)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.settings.effort_gains.name = []
      for i in range(0, length):
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1 = str[start:end].decode('utf-8')
        else:
          val1 = str[start:end]
        self.settings.effort_gains.name.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.effort_gains.kp = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.effort_gains.ki = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.effort_gains.kd = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.effort_gains.feed_forward = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.effort_gains.dead_zone = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.effort_gains.i_clamp = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.effort_gains.punch = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.effort_gains.min_target = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.effort_gains.max_target = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.effort_gains.target_lowpass = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.effort_gains.min_output = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.effort_gains.max_output = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.effort_gains.output_lowpass = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sB'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.effort_gains.d_on_error = struct.unpack(pattern, str[start:end])
      self.settings.effort_gains.d_on_error = map(bool, self.settings.effort_gains.d_on_error)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.name)
      buff.write(_struct_I.pack(length))
      for val1 in self.name:
        length = len(val1)
        if python3 or type(val1) == unicode:
          val1 = val1.encode('utf-8')
          length = len(val1)
        buff.write(struct.pack('<I%ss'%length, length, val1))
      length = len(self.position)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.position.tostring())
      length = len(self.velocity)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.velocity.tostring())
      length = len(self.effort)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.effort.tostring())
      length = len(self.settings.name)
      buff.write(_struct_I.pack(length))
      for val1 in self.settings.name:
        length = len(val1)
        if python3 or type(val1) == unicode:
          val1 = val1.encode('utf-8')
          length = len(val1)
        buff.write(struct.pack('<I%ss'%length, length, val1))
      length = len(self.settings.save_current_settings)
      buff.write(_struct_I.pack(length))
      pattern = '<%sB'%length
      buff.write(self.settings.save_current_settings.tostring())
      length = len(self.settings.control_strategy)
      buff.write(_struct_I.pack(length))
      pattern = '<%sb'%length
      buff.write(self.settings.control_strategy.tostring())
      length = len(self.settings.position_gains.name)
      buff.write(_struct_I.pack(length))
      for val1 in self.settings.position_gains.name:
        length = len(val1)
        if python3 or type(val1) == unicode:
          val1 = val1.encode('utf-8')
          length = len(val1)
        buff.write(struct.pack('<I%ss'%length, length, val1))
      length = len(self.settings.position_gains.kp)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.settings.position_gains.kp.tostring())
      length = len(self.settings.position_gains.ki)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.settings.position_gains.ki.tostring())
      length = len(self.settings.position_gains.kd)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.settings.position_gains.kd.tostring())
      length = len(self.settings.position_gains.feed_forward)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.settings.position_gains.feed_forward.tostring())
      length = len(self.settings.position_gains.dead_zone)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.settings.position_gains.dead_zone.tostring())
      length = len(self.settings.position_gains.i_clamp)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.settings.position_gains.i_clamp.tostring())
      length = len(self.settings.position_gains.punch)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.settings.position_gains.punch.tostring())
      length = len(self.settings.position_gains.min_target)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.settings.position_gains.min_target.tostring())
      length = len(self.settings.position_gains.max_target)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.settings.position_gains.max_target.tostring())
      length = len(self.settings.position_gains.target_lowpass)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.settings.position_gains.target_lowpass.tostring())
      length = len(self.settings.position_gains.min_output)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.settings.position_gains.min_output.tostring())
      length = len(self.settings.position_gains.max_output)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.settings.position_gains.max_output.tostring())
      length = len(self.settings.position_gains.output_lowpass)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.settings.position_gains.output_lowpass.tostring())
      length = len(self.settings.position_gains.d_on_error)
      buff.write(_struct_I.pack(length))
      pattern = '<%sB'%length
      buff.write(self.settings.position_gains.d_on_error.tostring())
      length = len(self.settings.velocity_gains.name)
      buff.write(_struct_I.pack(length))
      for val1 in self.settings.velocity_gains.name:
        length = len(val1)
        if python3 or type(val1) == unicode:
          val1 = val1.encode('utf-8')
          length = len(val1)
        buff.write(struct.pack('<I%ss'%length, length, val1))
      length = len(self.settings.velocity_gains.kp)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.settings.velocity_gains.kp.tostring())
      length = len(self.settings.velocity_gains.ki)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.settings.velocity_gains.ki.tostring())
      length = len(self.settings.velocity_gains.kd)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.settings.velocity_gains.kd.tostring())
      length = len(self.settings.velocity_gains.feed_forward)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.settings.velocity_gains.feed_forward.tostring())
      length = len(self.settings.velocity_gains.dead_zone)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.settings.velocity_gains.dead_zone.tostring())
      length = len(self.settings.velocity_gains.i_clamp)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.settings.velocity_gains.i_clamp.tostring())
      length = len(self.settings.velocity_gains.punch)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.settings.velocity_gains.punch.tostring())
      length = len(self.settings.velocity_gains.min_target)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.settings.velocity_gains.min_target.tostring())
      length = len(self.settings.velocity_gains.max_target)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.settings.velocity_gains.max_target.tostring())
      length = len(self.settings.velocity_gains.target_lowpass)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.settings.velocity_gains.target_lowpass.tostring())
      length = len(self.settings.velocity_gains.min_output)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.settings.velocity_gains.min_output.tostring())
      length = len(self.settings.velocity_gains.max_output)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.settings.velocity_gains.max_output.tostring())
      length = len(self.settings.velocity_gains.output_lowpass)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.settings.velocity_gains.output_lowpass.tostring())
      length = len(self.settings.velocity_gains.d_on_error)
      buff.write(_struct_I.pack(length))
      pattern = '<%sB'%length
      buff.write(self.settings.velocity_gains.d_on_error.tostring())
      length = len(self.settings.effort_gains.name)
      buff.write(_struct_I.pack(length))
      for val1 in self.settings.effort_gains.name:
        length = len(val1)
        if python3 or type(val1) == unicode:
          val1 = val1.encode('utf-8')
          length = len(val1)
        buff.write(struct.pack('<I%ss'%length, length, val1))
      length = len(self.settings.effort_gains.kp)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.settings.effort_gains.kp.tostring())
      length = len(self.settings.effort_gains.ki)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.settings.effort_gains.ki.tostring())
      length = len(self.settings.effort_gains.kd)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.settings.effort_gains.kd.tostring())
      length = len(self.settings.effort_gains.feed_forward)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.settings.effort_gains.feed_forward.tostring())
      length = len(self.settings.effort_gains.dead_zone)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.settings.effort_gains.dead_zone.tostring())
      length = len(self.settings.effort_gains.i_clamp)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.settings.effort_gains.i_clamp.tostring())
      length = len(self.settings.effort_gains.punch)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.settings.effort_gains.punch.tostring())
      length = len(self.settings.effort_gains.min_target)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.settings.effort_gains.min_target.tostring())
      length = len(self.settings.effort_gains.max_target)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.settings.effort_gains.max_target.tostring())
      length = len(self.settings.effort_gains.target_lowpass)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.settings.effort_gains.target_lowpass.tostring())
      length = len(self.settings.effort_gains.min_output)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.settings.effort_gains.min_output.tostring())
      length = len(self.settings.effort_gains.max_output)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.settings.effort_gains.max_output.tostring())
      length = len(self.settings.effort_gains.output_lowpass)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.settings.effort_gains.output_lowpass.tostring())
      length = len(self.settings.effort_gains.d_on_error)
      buff.write(_struct_I.pack(length))
      pattern = '<%sB'%length
      buff.write(self.settings.effort_gains.d_on_error.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.settings is None:
        self.settings = hebiros.msg.SettingsMsg()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.name = []
      for i in range(0, length):
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1 = str[start:end].decode('utf-8')
        else:
          val1 = str[start:end]
        self.name.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.position = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.velocity = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.effort = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.settings.name = []
      for i in range(0, length):
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1 = str[start:end].decode('utf-8')
        else:
          val1 = str[start:end]
        self.settings.name.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sB'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.save_current_settings = numpy.frombuffer(str[start:end], dtype=numpy.bool, count=length)
      self.settings.save_current_settings = map(bool, self.settings.save_current_settings)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sb'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.control_strategy = numpy.frombuffer(str[start:end], dtype=numpy.int8, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.settings.position_gains.name = []
      for i in range(0, length):
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1 = str[start:end].decode('utf-8')
        else:
          val1 = str[start:end]
        self.settings.position_gains.name.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.position_gains.kp = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.position_gains.ki = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.position_gains.kd = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.position_gains.feed_forward = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.position_gains.dead_zone = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.position_gains.i_clamp = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.position_gains.punch = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.position_gains.min_target = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.position_gains.max_target = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.position_gains.target_lowpass = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.position_gains.min_output = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.position_gains.max_output = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.position_gains.output_lowpass = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sB'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.position_gains.d_on_error = numpy.frombuffer(str[start:end], dtype=numpy.bool, count=length)
      self.settings.position_gains.d_on_error = map(bool, self.settings.position_gains.d_on_error)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.settings.velocity_gains.name = []
      for i in range(0, length):
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1 = str[start:end].decode('utf-8')
        else:
          val1 = str[start:end]
        self.settings.velocity_gains.name.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.velocity_gains.kp = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.velocity_gains.ki = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.velocity_gains.kd = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.velocity_gains.feed_forward = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.velocity_gains.dead_zone = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.velocity_gains.i_clamp = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.velocity_gains.punch = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.velocity_gains.min_target = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.velocity_gains.max_target = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.velocity_gains.target_lowpass = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.velocity_gains.min_output = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.velocity_gains.max_output = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.velocity_gains.output_lowpass = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sB'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.velocity_gains.d_on_error = numpy.frombuffer(str[start:end], dtype=numpy.bool, count=length)
      self.settings.velocity_gains.d_on_error = map(bool, self.settings.velocity_gains.d_on_error)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.settings.effort_gains.name = []
      for i in range(0, length):
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1 = str[start:end].decode('utf-8')
        else:
          val1 = str[start:end]
        self.settings.effort_gains.name.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.effort_gains.kp = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.effort_gains.ki = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.effort_gains.kd = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.effort_gains.feed_forward = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.effort_gains.dead_zone = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.effort_gains.i_clamp = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.effort_gains.punch = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.effort_gains.min_target = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.effort_gains.max_target = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.effort_gains.target_lowpass = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.effort_gains.min_output = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.effort_gains.max_output = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.effort_gains.output_lowpass = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sB'%length
      start = end
      end += struct.calcsize(pattern)
      self.settings.effort_gains.d_on_error = numpy.frombuffer(str[start:end], dtype=numpy.bool, count=length)
      self.settings.effort_gains.d_on_error = map(bool, self.settings.effort_gains.d_on_error)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
